### ISSUE TITLE
Add toString() methods to all request/response objects for easier debugging

### ISSUE THREAD

**Issue by DavidASeibert** [EMCECS/nfs-client-java#11]

**Comment by sgilhooly** [comment]
Not sure if it's considered a request/response object but [NfsStatus](https://github.com/EMCECS/nfs-client-java/blob/9328a0955274719c9baaa42fadc03ef78f04a329/src/main/java/com/emc/ecs/nfsclient/nfs/NfsStatus.java#L26) could also benefit from a `toString` to make error messages easier (possible) to diagnose. I'm curious why this class wasn't defined as an Enum which would have had a better default toString rendering but I'd settle for a better toString for sure. 

The error message currently shows:

<code>com.emc.ecs.nfsclient.nfs.NfsException: Error in NfsReaddirRequest serviceVersion:3 xid:-2034612967 usePrivilegedPort:false fileHandle:[1,2,3...] cookie:0 cookieverf0 error code:<b>com.emc.ecs.nfsclient.nfs.NfsStatus@177ed3d3</b></code>

**Comment by twincitiesguy** [comment]
I'm also not sure why this wasn't an enum, but probably to allow for additional (unknown) status codes.  In any case, this should be addressed by #42.
