### ISSUE TITLE
Add maven package info to README

### ISSUE THREAD

**Issue by mdvorak** [EMCECS/nfs-client-java#14]
This library is published to mvn central, however there is no information about it. Found it here:
https://mvnrepository.com/artifact/com.emc.ecs/nfs-client/1.0.3

Please following section (or improve it):

## Installation
You can download the library as Maven dependency from Maven Central Repository:
```
<dependency>
    <groupId>com.emc.ecs</groupId>
    <artifactId>nfs-client</artifactId>
    <version>1.0.3</version>
</dependency>
```

Thanks

**Comment by DavidASeibert** [comment]
Done.

**Comment by DavidASeibert** [comment]
Wiki link is not changed, as the Sonatype search engine somehow cannot find the latest version.
