### ISSUE TITLE
what is credential?

### ISSUE THREAD

**Issue by chansonzhang** [EMCECS/nfs-client-java#30]
If I know user and password of linux system, how can I get a credential?
Is there an example?
thanks

**Comment by twincitiesguy** [comment]
It's not clear what you're asking here.  NFSv3 does not use credentials, so I assume this question does not apply here.

**Comment by chansonzhang** [comment]
> It's not clear what you're asking here. NFSv3 does not use credentials, so I assume this question does not apply here.

Sorry, I'm asking about CredentialUnix, what is it? what is it used for? and how can it authorize the rpc call to remote serve in e.g. [this testcase](https://github.com/EMCECS/nfs-client-java/blob/8d157a625e50d05155a46600ffb06527be3fa6ed/src/test/java/com/emc/ecs/nfsclient/nfs/nfs3/Test_Nfs3.java#L51)
