### ISSUE TITLE
Error in NfsMkdirRequest serviceVersion:3 xid:-114604863 usePrivilegedPort:false fileHandle:

### ISSUE THREAD

**Issue by wangtingsong** [EMCECS/nfs-client-java#35]
Error in NfsMkdirRequest serviceVersion:3 xid:-114604863 usePrivilegedPort:false fileHandle:[1, 0, 7, 0, 5, 63, 18, 0, 0, 0, 0, 0, -13, 71, 104, -101, 119, 120, 73, -87, -81, -58, 13, -65, 15, -92, -57, -78] name:carModelAndSensor attributes:  [mode :510 uid: null gid: null size: null atime: timeSettingType:0, [seconds :0 nseconds: 0] mtime: timeSettingType:0, [seconds :0 nseconds: 0]] error code:com.emc.ecs.nfsclient.nfs.NfsStatus@4198b6b1

**Comment by twincitiesguy** [comment]
The detailed status message is not printed in the log, due to #11, which was implemented/fixed in #42.
